// src/components/Header.svelte
<div class="Header">
    <div class="Left">
        <img src="zufall-logo-color.png" alt="Zufall Logo Colored">
        <p>Zufall Labs</p>
    </div>
    <div class="Middle">
        <img src="menu-stripes.svg" alt="Menu stripes">
    </div>
    <div class="github-button">
        <a style="text-decoration: none" target="_blank" href="https://github.com/zufall-labs/">
            <div class="button">Github</div>
        </a>
    </div>
</div>


<style>
    @import '/src/lib/fonts.css';

    @media screen and (max-width: 480px) {
        .Header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            width: 90vw;
            height: 63px;
            background: linear-gradient(to right, #ECECEC, #FCFCFC, #ECECEC);
            border-radius: 7px;
            margin: 30px auto 0 auto;
        }

        .Header .Left {
            display: flex;
            height: 49px;
            width: 160px;
            margin-left: 7px;
        }

        .Header .Left img {
            width: 49px;
            border-radius: 7px;
        }

        .Header .Left p {
            margin-left: 10px;
            font-family: 'HelveticaNowDisplay', sans-serif;
            font-weight: bold;
        }

        .Middle {
            display: none;
        }

        .Header .github-button .button{
            display: flex;
            justify-content: center;
            align-items: center;
            width: 130px;
            height: 49px;
            border-radius: 7px;
            background: black;
            font-family: 'HelveticaNowDisplay', sans-serif;
            font-weight: bold;
            color: white;
            margin-right: 7px;
        }
    }

    @media (min-width: 1025px) {
        .Header {
            display: flex;
            align-items: center;
            margin: 63px auto 0 auto;
            height: 63px;
            width: 1344px;
            border-radius: 7px;
            background: linear-gradient(to right, #ECECEC, #FCFCFC, #ECECEC);
        }

        .Header .Left {
            display: flex;
            height: 49px;
            width: 160px;
            margin-left: 7px;
        }

        .Header .Left img {
            width: 49px;
            border-radius: 7px;
        }

        .Header .Left p {
            margin-left: auto;
            font-family: 'HelveticaNowDisplay', sans-serif;
            font-weight: bold;
        }

        .Header .Middle {
            margin: 0 auto;
        }

        .Header .github-button .button{
            display: flex;
            justify-content: center;
            align-items: center;
            margin-right: 7px;
            width: 130px;
            height: 49px;
            border-radius: 7px;
            background: black;
            font-family: 'HelveticaNowDisplay', sans-serif;
            font-weight: bold;
            color: white;
        }
    }

</style>

// app/components/Header.tsx
export default function Header() {
    return(
        <header className="flex h-16 w-full items-center rounded-lg bg-gradient-to-r from-[#ECECEC] via-[#FCFCFC] to-[#ECECEC] shadow-lg shadow-black/5 mobile:mx-auto mobile:mt-4 mobile:w-[85%] tablet:mx-auto tablet:w-[90%]">
            <div className="mr-auto flex h-16 items-center p-2">
                {/* Branding Logo */}
                <div className="h-12 w-12 rounded-lg bg-[url('/images/zufall-logo-color.png')] bg-cover bg-center bg-no-repeat"></div>

                {/* Branding Text */}
                <div className="ml-5 font-helvetica-now font-extrabold mobile:text-lg">Zufall Labs</div>
            </div>

            {/* Middle Accents */}
            <div className="absolute left-1/2 flex h-2 w-16 -translate-x-1/2 flex-col justify-between mobile:hidden">
                <div className="h-[2px] w-16 bg-[#7E7E7E]"></div>
                <div className="h-[2px] w-16 bg-[#7E7E7E]"></div>
            </div>

            {/* GitHub Button */}
            <a href="https://github.com/zufall-labs" target="_blank" rel="noreferrer" className="ml-auto mr-2">
                <button className="h-12 rounded-lg bg-black px-10 font-helvetica-now font-bold text-white">
                    GitHub
                </button>
            </a>
        </header>
    )
}
